rvm:
  - 2.1.5

before_install: gem update --remote bundler

before_script:
  - 'git submodule init'
  - 'git submodule update'
  - 'cd spec/dummy/'
  - 'cp .env.example ../../.env'
  - './bin/bootstrap'
  - 'bundle exec rake db:migrate'
  - 'cd ../../'

script:
  - 'bundle exec rake spec'
notifications:
  webhooks: https://ci.neighbor.ly/projects/356bc47e-0510-4049-8900-741bf9eda015/status
