rvm:
  - 2.1.1

before_install: gem update --remote bundler

before_script:
  - 'git submodule init'
  - 'git submodule update'
  - 'cd spec/dummy/'
  - './bin/bootstrap'
  - 'bundle exec rake db:migrate'
  - 'cd ../../'

script:
  - 'bundle exec rake spec'
